### ISSUE TITLE
Unable to login 'There is already an Authenticator'

### ISSUE THREAD

**Issue by K4r0qtuYNE5G4qgZ** [ShyPixie/steam-tools-ng#21]
I already tried multiple versions (0.7.2, 0.8, 0.9.1, 0.9.2)  and I always get stuck at login.

I also disabled every module but Steamgifts and also tried to call only that module via console, but even then it still wants to login to Steam which then fails with 'There's already an authenticator'.

Firstly why it wants to be an Authenticator if I disabled that module? Or is that error related to something else? 

I also use ASFui for idling cards on that machine, could that be the issue? But if so, there's still the question why it wants to login to Steam if only the Steamgifts module is enabled or called via console and nothing else.

And also running the now deprecated Steam Tools-2.0.2-Win64 works well with ASFui running, so it's either because steam-tools-ng now stubbornly wants to login to Steam even if it doesn't need to or some other issue.

**Comment by ShyPixie** [comment]
>  already tried multiple versions (0.7.2, 0.8, 0.9.1, 0.9.2) and I always get stuck at login.

Never do that, always use the lastest version.

> I also disabled every module but Steamgifts and also tried to call only that module via console, but even then it still wants to login to Steam which then fails with 'There's already an authenticator'.
> 
> Firstly why it wants to be an Authenticator if I disabled that module? Or is that error related to something else?
> 

When you disables authenticator, internally the other services still have to be logged in to work. You will always need to be logged on Steam platform for anything work, either by authenticating using STNG as authenticator (entering your username and password) or an external authenticator (entering the data manually in advanced settings). It's not an error.

> I also use ASFui for idling cards on that machine, could that be the issue? 

You can use anything for idling card. If you are going to do it I recommend you to deactivate the STNG card farming module because if you are running a lot of games at same time It can make you get banned.

> why it wants to login to Steam if only the Steamgifts module is enabled or called via console and nothing else.

Steamgifts is one of the services that use the SteamAPI to log in (via openid). (See https://www.steamgifts.com/?login)

> And also running the now deprecated Steam Tools-2.0.2-Win64 works well with ASFui running, so it's either because steam-tools-ng now stubbornly wants to login to Steam even if it doesn't need to or some other issue.

Steam Tools vanilla login is cracking your web browser cookies to login on Steam. Steam Tools NG login use your username and password to login on Steam without cracking anything, then you no longer need to have a web browser installed. It's a feature.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Thanks for clarify that, but there's still the question why I then get an 'There is already an Authenticator' error if I try to login. I also tried the latest 0.9.2 and it's the same, I enter username and password and then it fails with 'There is already an Authenticator'.

I also like I said disabled everything but the SG module, so STNG card farming is also disabled.

But also like I said everything Steam, ASFui and STNG is on same machine (Windows 10 1809 Build 17763.503), so could it be that if Steam and ASFui already is logged in, that STNG then can't login anymore and throws that 'There is already an Authenticator' error?

But ok I will anyway migrate both ASFui and STNG to an Raspberry pi 3 B+ and so it's positive that STNG doesn't need the cookies anymore, but I hope I can then have running both on the same pi and not again run into a 'There is already an Authenticator' error.

**Comment by ShyPixie** [comment]
It's not related. If you get "There is already an Authenticator" is because there is already an Authenticator on your **Steam Account**... Steam doesn't allow two or more authenticator. So disables your authenticator and try to login again or insert the data manually if you want to use another authenticator that not STNG.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
I suppose that ASF then logins as one, because there is nothing else that also needs to login to Steam. So it's probably impossible to have ASF and STNG running and logged in on the same machine then.

I quickly tested that now by shutdown ASF/ASFui and trying to login with STNG 0.92 --> Doesn't work, you already have an Authenticator etc. So i'm sorry but I don't see where the problem should be and will simply continue using ST 2.02 which works.

Also strange that ASF doesn't seem to have any problems like this and I can also login with multiple instances just fine in different browsers on the same machine.

Or also what you mean with Authenticator is the Steamguard/Steam Mobile App but if so, well, I can't and won't disable it because of the restrictions that then apply and I also need the codes for the various machines Steam runs on. And if you mean the shared secrets of that app with "insert the data manually" that's also impossible on a unrooted iPhone. So if it's that what you mean then the situation is fubar.

**Comment by ShyPixie** [comment]
> Or also what you mean with Authenticator is the Steamguard/Steam Mobile App but if so, well, I can't and won't disable it because of the restrictions that then apply and I also need the codes for the various machines Steam runs on. And if you mean the shared secrets of that app with "insert the data manually" that's also impossible on a unrooted iPhone. So if it's that what you mean then the situation is fubar.

STNG is built to replace mobile authenticator. If you use STNG as an authenticator you WILL HAVE the codes, the confirmations, and everything else exactly like official app, but portable. Insert data manually is not a requirement, it's an advanced feature for advanced users.

**Comment by ShyPixie** [comment]
> Also strange that ASF doesn't seem to have any problems like this and I can also login with multiple instances just fine in different browsers on the same machine.

You must understand that the Steam Platform have a lot of different ways to login and access APIs and services. Vanilla Steam Tools and ASF (probably) uses a simple login process that Steam will recognize as a normal computer login. STNG uses a more complex login process that Steam will recognize as Steam Mobile App and it will provide access to internal SteamGuard APIs and private Steam APIs that is needed to more cool functions. So, to Steam STNG "IS" a phone... nothing that you do will remove the message that you already have an Authenticator if you don't remove your already active authenticator. Inserting the data manually (you can get that from vanilla ST config files if it's working for you) will just tell to STNG use simple login (computer) instead mobile login, and it will disable a lot of functions.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
The issue is that STNG requires to become an Authenticator or the TOTP secrets to login, while for ASF this is optional. If I only provide username&password and Steam Mobile Authenticator is active on the account then ASF simply asks for the 2FA code to be entered just like steam client and browsers do.

ASF also has an ASF 2FA mode where it then needs to become an Authenticator or needs the TOTP secrets and device id from the Steam Mobile Authenticator so that the user don't need to enter any 2FA codes anymore and ASF can accept trade confirmations etc.

But that data (shared secret for TOTP, device id for trade confirmations etc.) aren't easy to get without rooting the phone or using some exploits, I was lucky and there was an exploit on my phone else I would had to root it.

But once you have that data, it doesn't matter anymore if there's a Steam Mobile Authenticator active or not on the phone, you can generate 2FA codes and accept trade notifications on the Phone, Winauth, ASF, SDA, and I hope also STNG.

Also consider to make STNG a bit more convenient and hassle free, especially for users that already have a Steam Mobile Authenticator active on their phone/account, and don't require STNG to become an Authenticator or require the TOTP secrets to login anymore. Instead do it like ASF and then simply request the 2FA code to be entered on login . That way at least everything but accepting trade confirmations will work. Users that also needs STNG to accept trade confirmations etc. then still can make STNG an Authenticator or getting the TOTP secrets and device id from the phone if they want, just like it's also optionally possible with ASF.

**Comment by ShyPixie** [comment]
I don't see any reason to use STNG if you are going to use just one module and not confirmations, because you can found much simpler scripts to enter giveaways, drop cards, etc. You have a point with the login issue, but instead you can ask yourself:

1) Why I need ASF?
2) Why I need official Steam Mobile App?
3) Why I need STNG?

So, if you realize that you REALLY need to use STNG, ask again: What STNG is missing?

So you can open feature requests and I would be glad to make it, because it makes no sense for you to use STNG if you can't have everything you need in it. That's what it's for, but I can't know what you need if you do not tell me what you need.

I will close this issue. Open a new issue/request if you need something more.
